export const REQUEST_MANIFEST = 'REQUEST_MANIFEST'
export const REQUEST_SERVER = 'REQUEST_SERVER'


export const RECEIVE_MANIFEST = 'RECEIVE_MANIFEST'
export const LAUNCH_IIIF = 'LAUNCH_IIIF'
export const NULLIFY_SERVER = 'NULLIFY_SERVER'
export const NULLIFY_MANIFEST = 'NULLIFY_MANIFEST'
export const RECEIVE_SERVER = 'RECEIVE_SERVER'

export const CURRENT_BG_POS = 'CURRENT_BG_POS'
export const SET_CURRENT_ITEM = 'SET_CURRENT_ITEM'
export const SET_LANG = 'SET_LANG'
export const SET_TAB = 'SET_TAB'

export const RECEIVE_ERROR = 'RECEIVE_ERROR'